# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fc206e3b6025192ab9d4d7b5536262edd58c34995302bd9e42068de244b4c9cd261a6cdf5f549bfc8bbcbcfeb1945b568fa03fb56d068f12c2aa7308df5413f

test:
  secret_key_base: c712eda5e84227d1c3319174e242e32f512373803451fbe17c9567eaf7b2f26bbdc6478943d56d0c3311d9852a9694402c60d07f9c8345fd7b68c9d0481d548f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
